# Generated by Django 5.2 on 2026-05-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sql_execute", "0002_sqlexecutionrequest_running_tip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sqlexecutionrequest",
            options={"ordering": ["-release_date", "-id"]},
        ),
    ]
