# Generated by Django 6.0.4 on 2026-04-22 07:01

from django.db import migrations, models


def _seed_role_permission_policies(apps, schema_editor):
    RolePermissionPolicy = apps.get_model("accounts", "RolePermissionPolicy")
    defaults_by_role = {
        "ops": {
            "menu_release_track": True,
            "menu_branch_create": True,
            "menu_release_entry": True,
            "menu_hobo_ledger": True,
            "menu_sql_execute": True,
            "menu_admin_config": False,
            "action_release_track_use": True,
            "action_branch_task_preview": True,
            "action_branch_task_execute_release": True,
            "action_branch_task_execute_hobo": True,
            "action_schedule_manage": True,
            "action_release_batch_manage": True,
            "action_release_item_create": False,
            "action_release_item_edit_dev_fields": False,
            "action_release_item_edit_ops_fields": True,
            "action_release_item_delete_own": False,
            "action_hobo_item_create": False,
            "action_hobo_item_edit_own": False,
            "action_hobo_item_delete_own": False,
            "action_sql_repo_sync": False,
            "action_sql_request_apply": False,
            "action_sql_request_approve": False,
            "data_scope_release_entry": "all",
            "data_scope_hobo_ledger": "all",
            "data_scope_sql_requests": "self",
        },
        "developer": {
            "menu_release_track": False,
            "menu_branch_create": False,
            "menu_release_entry": True,
            "menu_hobo_ledger": True,
            "menu_sql_execute": True,
            "menu_admin_config": False,
            "action_release_track_use": False,
            "action_branch_task_preview": False,
            "action_branch_task_execute_release": False,
            "action_branch_task_execute_hobo": False,
            "action_schedule_manage": False,
            "action_release_batch_manage": False,
            "action_release_item_create": True,
            "action_release_item_edit_dev_fields": True,
            "action_release_item_edit_ops_fields": False,
            "action_release_item_delete_own": True,
            "action_hobo_item_create": True,
            "action_hobo_item_edit_own": True,
            "action_hobo_item_delete_own": True,
            "action_sql_repo_sync": False,
            "action_sql_request_apply": True,
            "action_sql_request_approve": False,
            "data_scope_release_entry": "all",
            "data_scope_hobo_ledger": "all",
            "data_scope_sql_requests": "self",
        },
    }
    for role, values in defaults_by_role.items():
        RolePermissionPolicy.objects.get_or_create(role=role, defaults=values)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_gitplatformconfig_sql_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermissionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ops", "运维"), ("developer", "研发")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("menu_release_track", models.BooleanField(default=False)),
                ("menu_branch_create", models.BooleanField(default=False)),
                ("menu_release_entry", models.BooleanField(default=False)),
                ("menu_hobo_ledger", models.BooleanField(default=False)),
                ("menu_sql_execute", models.BooleanField(default=False)),
                ("menu_admin_config", models.BooleanField(default=False)),
                ("action_release_track_use", models.BooleanField(default=False)),
                ("action_branch_task_preview", models.BooleanField(default=False)),
                (
                    "action_branch_task_execute_release",
                    models.BooleanField(default=False),
                ),
                ("action_branch_task_execute_hobo", models.BooleanField(default=False)),
                ("action_schedule_manage", models.BooleanField(default=False)),
                ("action_release_batch_manage", models.BooleanField(default=False)),
                ("action_release_item_create", models.BooleanField(default=False)),
                (
                    "action_release_item_edit_dev_fields",
                    models.BooleanField(default=False),
                ),
                (
                    "action_release_item_edit_ops_fields",
                    models.BooleanField(default=False),
                ),
                ("action_release_item_delete_own", models.BooleanField(default=False)),
                ("action_hobo_item_create", models.BooleanField(default=False)),
                ("action_hobo_item_edit_own", models.BooleanField(default=False)),
                ("action_hobo_item_delete_own", models.BooleanField(default=False)),
                ("action_sql_repo_sync", models.BooleanField(default=False)),
                ("action_sql_request_apply", models.BooleanField(default=False)),
                ("action_sql_request_approve", models.BooleanField(default=False)),
                (
                    "data_scope_release_entry",
                    models.CharField(
                        choices=[("self", "仅本人"), ("all", "全部")],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "data_scope_hobo_ledger",
                    models.CharField(
                        choices=[("self", "仅本人"), ("all", "全部")],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "data_scope_sql_requests",
                    models.CharField(
                        choices=[("self", "仅本人"), ("all", "全部")],
                        default="self",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "角色权限策略",
                "verbose_name_plural": "角色权限策略",
                "db_table": "role_permission_policy",
            },
        ),
        migrations.RunPython(_seed_role_permission_policies, migrations.RunPython.noop),
    ]
