# Generated by Django 6.0.4 on 2026-04-22 08:11

from django.db import migrations, models


def _seed_release_entry_editable_fields(apps, schema_editor):
    RolePermissionPolicy = apps.get_model("accounts", "RolePermissionPolicy")
    default_dev_fields = [
        "project_id",
        "branch_type",
        "requirement_branch",
        "release_branch",
        "flow_name",
        "biz_category",
        "tech_owner",
        "biz_owner",
        "common_component_branch",
        "need_param_release",
        "param_confirmed",
        "need_menu",
        "menu_added",
        "need_difs",
        "need_flowchart",
        "flowchart_checked",
        "flow_definition_name",
        "implementation_unit_no",
        "remark",
        "need_event_platform",
        "need_task_pool",
        "need_bpmp",
        "need_image",
        "need_esf",
        "need_trade_tuning",
        "need_release_verify",
        "rel_test_status",
    ]
    default_ops_fields = [
        "rel_deployed",
        "deploy_status",
    ]
    for policy in RolePermissionPolicy.objects.select_related("role").all():
        role_key = getattr(policy.role, "key", "")
        if role_key == "ops":
            policy.release_entry_editable_fields = default_ops_fields
        elif role_key == "developer":
            policy.release_entry_editable_fields = default_dev_fields
        else:
            policy.release_entry_editable_fields = []
        policy.save(update_fields=["release_entry_editable_fields"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_roledefinition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepermissionpolicy",
            name="release_entry_editable_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(_seed_release_entry_editable_fields, migrations.RunPython.noop),
    ]
