# Generated by Django 6.0.4 on 2026-05-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rolepermissionpolicy_action_auto_export_hobo_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermissionpolicy',
            name='menu_export_schedule',
            field=models.BooleanField(default=False, verbose_name='定时导出配置'),
        ),
    ]
