# Generated by Django 6.0.4 on 2026-04-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0002_releasebatch_release_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="工程编码"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=128, verbose_name="工程名称"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "project_catalog",
                "ordering": ["project_name", "id"],
            },
        ),
    ]
