# Generated by Django 6.0.4 on 2026-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0004_alter_projectcatalog_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseitem",
            name="deploy_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
