# Generated by Django 6.0.4 on 2026-04-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0007_hobo_requirement_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseitem",
            name="biz_category",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
