# Generated by Django 6.0.4 on 2026-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branch_create", "0011_execute_run_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseitem",
            name="implementation_unit_no",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
