# Generated by Django 6.0.4 on 2026-04-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branch_create", "0012_releaseitem_implementation_unit_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseitem",
            name="remark",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
