# Generated by Django 6.0.4 on 2026-05-09 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0020_alter_hoborequirementledger_base_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="releaseitem",
            name="need_config_release",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ExportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("cron_expr", models.CharField(max_length=64)),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("hobo_ledger", "HOBO需求登记台账"),
                            ("release_entry", "投产征集"),
                        ],
                        max_length=32,
                        verbose_name="导出类型",
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "export_schedule",
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
