# Generated by Django 5.2 on 2026-05-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0021_alter_releaseitem_need_config_release_exportschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseitem",
            name="bug_reporter",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="releaseitem",
            name="is_bug_fix",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
