# Generated by Django 5.2 on 2026-05-29 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0024_releaseitem_bug_discovery_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoborequirementledger",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="releaseitem",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="hoborequirementledger",
            name="requirement_branch",
            field=models.CharField(
                max_length=68,
                validators=[
                    django.core.validators.RegexValidator(
                        message="分支名称格式不正确",
                        regex="^(FIX|REQ|PUB)-[0-9]{8}-[0-9]{4}(-[\\w-]{1,50})?$",
                    )
                ],
                verbose_name="分支名称",
            ),
        ),
    ]
