RELEASE_ENTRY_FIELD_OPTIONS = [
    ("project_id", "工程"),
    ("branch_type", "分支类型"),
    ("requirement_branch", "需求分支"),
    ("release_branch", "投产分支"),
    ("flow_name", "流程名称"),
    ("biz_category", "业务分类"),
    ("tech_owner", "技术负责人"),
    ("biz_owner", "业务负责人"),
    ("common_component_branch", "通用组件分支"),
    ("need_param_release", "需要参数投产"),
    ("param_confirmed", "参数已确认"),
    ("need_menu", "需要菜单"),
    ("menu_added", "菜单已新增"),
    ("need_difs", "需要 DIFS"),
    ("need_flowchart", "需要流程图"),
    ("flowchart_checked", "流程图已核对"),
    ("flow_definition_name", "流程定义名称"),
    ("implementation_unit_no", "实施单元编号"),
    ("remark", "备注"),
    ("need_event_platform", "需要事件平台"),
    ("need_task_pool", "需要任务池"),
    ("need_bpmp", "需要 BPMP"),
    ("need_image", "需要镜像"),
    ("need_esf", "需要 ESF"),
    ("need_trade_tuning", "需要交易调优"),
    ("need_release_verify", "需要投产验证"),
    ("rel_test_status", "REL 测试状态"),
    ("rel_deployed", "REL 是否已部署"),
    ("deploy_status", "部署状态"),
]

RELEASE_ENTRY_DEV_FIELD_KEYS = {
    "project_id",
    "branch_type",
    "requirement_branch",
    "release_branch",
    "flow_name",
    "biz_category",
    "tech_owner",
    "biz_owner",
    "common_component_branch",
    "need_param_release",
    "param_confirmed",
    "need_menu",
    "menu_added",
    "need_difs",
    "need_flowchart",
    "flowchart_checked",
    "flow_definition_name",
    "implementation_unit_no",
    "remark",
    "need_event_platform",
    "need_task_pool",
    "need_bpmp",
    "need_image",
    "need_esf",
    "need_trade_tuning",
    "need_release_verify",
    "rel_test_status",
}

RELEASE_ENTRY_OPS_FIELD_KEYS = {
    "rel_deployed",
    "deploy_status",
}

DEFAULT_RELEASE_ENTRY_FIELDS_BY_ROLE_KEY = {
    "ops": sorted(RELEASE_ENTRY_OPS_FIELD_KEYS),
    "developer": sorted(RELEASE_ENTRY_DEV_FIELD_KEYS),
}
