# Generated by Django 6.0.4 on 2026-04-20 08:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(unique=True, verbose_name="投产日期"),
                ),
                (
                    "release_branch",
                    models.CharField(max_length=64, verbose_name="投产分支"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("open", "开放填写"),
                            ("closed", "关闭填写"),
                            ("executed", "已执行"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_release_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "release_batch",
                "ordering": ["-release_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseBatchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_code", models.CharField(max_length=64)),
                ("project_name", models.CharField(max_length=128)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="branch_create.releasebatch",
                    ),
                ),
            ],
            options={
                "db_table": "release_batch_project",
                "ordering": ["project_name", "id"],
                "unique_together": {("batch", "project_code")},
            },
        ),
        migrations.CreateModel(
            name="ReleaseBranchSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_type",
                    models.CharField(
                        choices=[("FIX", "FIX"), ("REQ", "REQ"), ("PUB", "PUB")],
                        max_length=3,
                    ),
                ),
                ("date_str", models.CharField(max_length=8)),
                ("current_serial", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "release_branch_sequence",
                "unique_together": {("branch_type", "date_str")},
            },
        ),
        migrations.CreateModel(
            name="ReleaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_type",
                    models.CharField(
                        choices=[("FIX", "FIX"), ("REQ", "REQ"), ("PUB", "PUB")],
                        default="REQ",
                        max_length=3,
                    ),
                ),
                (
                    "requirement_branch",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="需求分支格式不正确",
                                regex="^(FIX|REQ|PUB)-[0-9]{8}-[0-9]{4}$",
                            )
                        ],
                    ),
                ),
                ("flow_name", models.CharField(max_length=128)),
                ("release_branch", models.CharField(max_length=64)),
                ("tech_owner", models.CharField(max_length=64)),
                ("biz_owner", models.CharField(max_length=64)),
                ("need_param_release", models.BooleanField(blank=True, null=True)),
                ("param_confirmed", models.BooleanField(blank=True, null=True)),
                ("need_menu", models.BooleanField(blank=True, null=True)),
                ("menu_added", models.BooleanField(blank=True, null=True)),
                ("need_difs", models.BooleanField(blank=True, null=True)),
                ("need_flowchart", models.BooleanField(blank=True, null=True)),
                ("flowchart_checked", models.BooleanField(blank=True, null=True)),
                (
                    "flow_definition_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("need_event_platform", models.BooleanField(blank=True, null=True)),
                ("need_task_pool", models.BooleanField(blank=True, null=True)),
                ("need_bpmp", models.BooleanField(blank=True, null=True)),
                ("need_image", models.BooleanField(blank=True, null=True)),
                ("need_esf", models.BooleanField(blank=True, null=True)),
                ("need_trade_tuning", models.BooleanField(blank=True, null=True)),
                ("need_release_verify", models.BooleanField(blank=True, null=True)),
                (
                    "common_component_branch",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("rel_deployed", models.BooleanField(blank=True, null=True)),
                (
                    "rel_test_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "line_status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("incomplete", "未填写完整"),
                            ("submitted", "已提交"),
                            ("confirmed", "已确认"),
                            ("rejected", "已驳回"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="branch_create.releasebatch",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_items",
                        to="branch_create.releasebatchproject",
                    ),
                ),
            ],
            options={
                "db_table": "release_item",
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
