# Generated by Django 6.0.4 on 2026-04-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasebatch",
            name="release_type",
            field=models.CharField(
                choices=[("release", "release"), ("hotfix", "hotfix")],
                default="release",
                max_length=16,
                verbose_name="投产分支类型",
            ),
        ),
    ]
