# Generated by Django 6.0.4 on 2026-04-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0003_projectcatalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcatalog",
            name="project_name",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="工程名称"
            ),
        ),
    ]
