# Generated by Django 6.0.4 on 2026-04-21 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0008_release_item_biz_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hoborequirementledger",
            name="branch_create_error",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="hoborequirementledger",
            name="branch_created",
            field=models.BooleanField(default=False, verbose_name="是否已建分支"),
        ),
        migrations.AddField(
            model_name="hoborequirementledger",
            name="branch_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="建分支时间"
            ),
        ),
        migrations.AddField(
            model_name="hoborequirementledger",
            name="branch_created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_hobo_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="releaseitem",
            name="branch_create_error",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="releaseitem",
            name="branch_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="releaseitem",
            name="branch_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="releaseitem",
            name="branch_created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_release_item_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="BranchCreateSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("cron_expr", models.CharField(max_length=64)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("hobo", "HOBO需求登记"),
                            ("release", "投产征集"),
                            ("both", "两者"),
                        ],
                        default="both",
                        max_length=16,
                    ),
                ),
                ("days_back", models.PositiveIntegerField(default=30)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branch_create_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "branch_create_schedule",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BranchCreateScheduleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                (
                    "trigger_mode",
                    models.CharField(
                        choices=[("manual", "手动"), ("cron", "计划任务")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                ("log", models.TextField(blank=True, default="")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="branch_create.branchcreateschedule",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branch_schedule_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "branch_create_schedule_run",
                "ordering": ["-started_at", "-id"],
            },
        ),
    ]
