# Generated by Django 6.0.4 on 2026-04-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0009_schedule_and_branch_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoborequirementledger",
            name="branch_create_log",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="releaseitem",
            name="branch_create_log",
            field=models.TextField(blank=True, default=""),
        ),
    ]
