# Generated by Django 5.2.13 on 2026-04-23 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0014_releaseitem_sql_only_release"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releaseitem",
            name="requirement_branch",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="需求分支格式不正确",
                        regex="^(FIX|REQ|PUB)-[0-9]{8}-[0-9]{4}$",
                    )
                ],
            ),
        ),
    ]
