# Generated by Django 5.2 on 2026-05-18 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0022_releaseitem_bug_fix_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportschedule",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name="exportschedule",
            constraint=models.UniqueConstraint(
                fields=("name", "export_type"), name="unique_name_per_export_type"
            ),
        ),
    ]
