# Generated by Django 5.2 on 2026-05-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0023_export_schedule_unique_name_per_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseitem",
            name="bug_discovery_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
