# Generated by Django 5.2 on 2026-05-29 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_create", "0025_hoborequirementledger_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releaseitem",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="release_items",
                to="branch_create.releasebatchproject",
            ),
        ),
    ]
