# =========================
# 全局配置
# =========================
TAG_NAME=20260407_v1
MERGE_MESSAGE=20260407投产追板
TAG_MESSAGE=20260407投产变更

# =========================
# 仓库配置
# 格式：
# repo_name|release_branch|target_branch
# =========================
hobo-payment-front|hotfix-20260407|master
hobo-flow-config|hotfix-20260407|master
hobo-pub-flow|hotfix-20260407|master
# hobo-wf|hotfix-20260407|master
hobo-work-front|hotfix-20260407|master
