# Generated by Django 6.0.4 on 2026-04-22 07:25

import django.db.models.deletion
from django.db import migrations, models


def _safe_key(raw: str, used: set[str]) -> str:
    base = "".join(ch for ch in (raw or "").lower() if ch.isalnum() or ch == "_")
    base = base[:24] or "role"
    key = base
    index = 1
    while key in used:
        suffix = f"_{index}"
        key = f"{base[:24 - len(suffix)]}{suffix}"
        index += 1
    used.add(key)
    return key


def _migrate_roles_to_definition(apps, schema_editor):
    RoleDefinition = apps.get_model("accounts", "RoleDefinition")
    UserProfile = apps.get_model("accounts", "UserProfile")
    RolePermissionPolicy = apps.get_model("accounts", "RolePermissionPolicy")

    role_name_map = {
        "ops": "运维",
        "developer": "研发",
    }
    used_keys: set[str] = set()
    role_map: dict[str, object] = {}

    legacy_roles = set(
        UserProfile.objects.values_list("role", flat=True).distinct()
    ) | set(RolePermissionPolicy.objects.values_list("role", flat=True).distinct())
    for legacy in sorted(v for v in legacy_roles if v):
        key = _safe_key(str(legacy), used_keys)
        role_obj, _ = RoleDefinition.objects.get_or_create(
            key=key,
            defaults={
                "name": role_name_map.get(legacy, str(legacy)),
                "is_system": legacy in {"ops", "developer"},
                "enabled": True,
                "can_be_registered": legacy in {"ops", "developer"},
                "is_staff_role": legacy == "ops",
            },
        )
        role_map[str(legacy)] = role_obj

    if "developer" not in role_map:
        role_obj, _ = RoleDefinition.objects.get_or_create(
            key="developer",
            defaults={
                "name": "研发",
                "is_system": True,
                "enabled": True,
                "can_be_registered": True,
                "is_staff_role": False,
            },
        )
        role_map["developer"] = role_obj

    default_role = role_map["developer"]
    for profile in UserProfile.objects.all():
        profile.role_ref_id = role_map.get(str(profile.role), default_role).id
        profile.save(update_fields=["role_ref"])

    for policy in RolePermissionPolicy.objects.all():
        policy.role_ref_id = role_map.get(str(policy.role), default_role).id
        policy.save(update_fields=["role_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rolepermissionpolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("is_system", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("can_be_registered", models.BooleanField(default=False)),
                ("is_staff_role", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "角色定义",
                "verbose_name_plural": "角色定义",
                "db_table": "role_definition",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="rolepermissionpolicy",
            name="action_hobo_item_edit_others",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rolepermissionpolicy",
            name="action_release_item_edit_others",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rolepermissionpolicy",
            name="action_sql_request_edit_others",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounts.roledefinition",
            ),
        ),
        migrations.AddField(
            model_name="rolepermissionpolicy",
            name="role_ref",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="accounts.roledefinition",
            ),
        ),
        migrations.RunPython(_migrate_roles_to_definition, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="role_ref",
            new_name="role",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="accounts.roledefinition",
            ),
        ),
        migrations.RemoveField(
            model_name="rolepermissionpolicy",
            name="role",
        ),
        migrations.RenameField(
            model_name="rolepermissionpolicy",
            old_name="role_ref",
            new_name="role",
        ),
        migrations.AlterField(
            model_name="rolepermissionpolicy",
            name="role",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_policy",
                to="accounts.roledefinition",
            ),
        ),
    ]
