# Generated by Django 5.2.13 on 2026-04-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_gitplatformconfig_sql_auto_approve_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepermissionpolicy",
            name="menu_notification",
            field=models.BooleanField(default=False, verbose_name="通知铃铛可见"),
        ),
    ]
