# Generated by Django 6.0.4 on 2026-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_rolepermissionpolicy_action_hobo_ledger_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepermissionpolicy",
            name="action_auto_export_hobo_ledger",
            field=models.BooleanField(
                default=False, verbose_name="HOBO需求登记定时导出"
            ),
        ),
        migrations.AddField(
            model_name="rolepermissionpolicy",
            name="action_auto_export_release_entry",
            field=models.BooleanField(default=False, verbose_name="投产征集定时导出"),
        ),
    ]
