# Generated by Django 6.0.4 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_menu_export_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermissionpolicy',
            name='action_sql_request_delete',
            field=models.BooleanField(default=False, verbose_name='删除SQL执行记录'),
        ),
    ]
